[package]
name = "learning-rust-alura"
version = "0.1.0"
edition = "2021"
authors = ["Fabio Molliet <fabiomolliet@hotmail.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
